variables:
  IMG_NAME: "registry.gitlab.com/${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}"
  IMG_TAG: "${CI_COMMIT_REF_SLUG}"
  IMG: "${IMG_NAME}:${IMG_TAG}"

build:
  image: docker:18.09
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  services:
    - name: docker:20-dind
      alias: docker
      command: [ "--tls=false" ]
  stage: build
  script:
    - docker login -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD} ${CI_REGISTRY}
    - docker build -t $IMG -f ./Dockerfile .
    - docker push $IMG
  only:
    - main
    - next
  tags:
    - build

deploy:
  image: alpine/helm:3.2.1
  stage: deploy
  script:
    - helm upgrade --install 
      "${CI_PROJECT_NAME}.production"
      --namespace pasles.net
      --set name="web-prod"
      --set domainName="pasles.net"
      --set image.repository="${IMG_NAME}"
      --set image.tag="${IMG_TAG}"
      --set tls.enabled="true"
      --set tls.secretName="prod-pasles-net-tls"
      --create-namespace
      .ci/chart
  environment:
    name: review/$CI_COMMIT_REF_NAME
    url: https:/werify/pasles.net
  only:
    - main
  needs: ["build"]

deploy_next:
  image: alpine/helm:3.2.1
  stage: deploy
  script:
    - helm upgrade --install 
      "${CI_PROJECT_NAME}.next"
      --namespace pasles.net
      --set name="web-next"
      --set domainName="next.pasles.net"
      --set image.repository="${IMG_NAME}"
      --set image.tag="${IMG_TAG}"
      --set tls.enabled="true"
      --set tls.secretName="next-pasles-net-tls"
      --create-namespace
      .ci/chart
  environment:
    name: review/$CI_COMMIT_REF_NAME
    url: https://next.pasles.net
  only:
    - next
  needs: ["build"]
