name: "sample"
replicaCount: 1

ingressController: nginx

service:
  type: ClusterIP

domainName: "pasles.net"

tls:
  enabled: false
  clusterIssuer: cf-letsencrypt
  secretName: pasles-net-wildcard-tls

image:
  repository: "Werify.{{ .Values.name }}-web"
  pullPolicy: Always
  tag: latest

resources: {}
tolerations: {}
